module.exports = [{ "index": 0, "type": "CLASS", "token": "class" },
    { "index": 6, "type": "ID", "token": "HelloWorld" },
    { "index": 18, "type": "LEFT_CURLY_B", "token": "{" },
    { "index": 22, "type": "PUBLIC", "token": "public" },
    { "index": 29, "type": "STATIC", "token": "static" },
    { "index": 36, "type": "VOID", "token": "void" },
    { "index": 41, "type": "MAIN", "token": "main" },
    { "index": 45, "type": "LEFT_ROUND_B", "token": "(" },
    { "index": 46, "type": "STRING", "token": "String" },
    { "index": 52, "type": "LEFT_SQUARE_B", "token": "[" },
    { "index": 53, "type": "RIGHT_SQUARE_B", "token": "]" },
    { "index": 55, "type": "ID", "token": "args" },
    { "index": 59, "type": "RIGHT_ROUND_B", "token": ")" },
    { "index": 61, "type": "LEFT_CURLY_B", "token": "{" },
    { "index": 70, "type": "IF", "token": "if" },
    { "index": 72, "type": "LEFT_ROUND_B", "token": "(" },
    { "index": 74, "type": "ID", "token": "y" },
    { "index": 77, "type": "EQUAL", "token": "=" },
    { "index": 78, "type": "EQUAL", "token": "=" },
    { "index": 79, "type": "INTEGRAL_LITERAL", "token": "3" },
    { "index": 81, "type": "RIGHT_ROUND_B", "token": ")" },
    {
        "index": 86,
        "type": "SYSTEM.OUT.PRINTLN",
        "token": "System.out.println"
    },
    { "index": 104, "type": "LEFT_ROUND_B", "token": "(" },
    { "index": 105, "type": "STRING_LITERAL", "token": "\"hello 1\"" },
    { "index": 114, "type": "RIGHT_ROUND_B", "token": ")" },
    { "index": 115, "type": "SEMICOLON", "token": ";" },
    { "index": 124, "type": "IF", "token": "if" },
    { "index": 126, "type": "LEFT_ROUND_B", "token": "(" },
    { "index": 128, "type": "ID", "token": "y" },
    { "index": 129, "type": "LEFT_SQUARE_B", "token": "[" },
    { "index": 131, "type": "RIGHT_SQUARE_B", "token": "]" },
    { "index": 133, "type": "NOT", "token": "!" },
    { "index": 134, "type": "EQUAL", "token": "=" },
    { "index": 135, "type": "INTEGRAL_LITERAL", "token": "5" },
    { "index": 137, "type": "RIGHT_ROUND_B", "token": ")" },
    { "index": 143, "type": "ID", "token": "x" },
    { "index": 145, "type": "EQUAL", "token": "=" },
    { "index": 146, "type": "INTEGRAL_LITERAL", "token": "5" },
    { "index": 148, "type": "SEMICOLON", "token": ";" },
    { "index": 153, "type": "ELSE", "token": "else" },
    { "index": 162, "type": "ID", "token": "x" },
    { "index": 164, "type": "LEFT_SQUARE_B", "token": "[" },
    { "index": 166, "type": "RIGHT_SQUARE_B", "token": "]" },
    { "index": 167, "type": "EQUAL", "token": "=" },
    { "index": 168, "type": "INTEGRAL_LITERAL", "token": "10" },
    { "index": 171, "type": "SEMICOLON", "token": ";" },
    { "index": 175, "type": "RIGHT_CURLY_B", "token": "}" },
    { "index": 178, "type": "RIGHT_CURLY_B", "token": "}" }
];